# This is a basic workflow to help you get started with Actions

name: 'deploy for ailiyun'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: 安装解压程序
      run: sudo apt-get update && sudo apt-get install -y unzip

    - name: 安装Funcraft
      run: wget --no-check-certificate -O fun-linux.zip https://gosspublic.alicdn.com/fun/fun-v3.6.14-linux.zip && unzip fun-linux.zip && sudo mv fun-*-linux /usr/local/bin/fun && rm fun-linux.zip

    - name: 配置用户信息
      run: echo '${{ secrets.biliconfig }}' > ./config/config.json
    
    - name: 部署至阿里云
      run: fun deploy -t aliyun-serverless-template.yml
      env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          REGION: cn-shanghai
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
