name: 'deploy for aliyun'

on:
  workflow_dispatch:
  watch:
    types: started

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2

    - name: 安装python3，requests和unzip
      run: sudo apt-get update && sudo apt-get install -y python3.8 python-requests unzip

    - name: 配置用户信息并检查有效性
      run: echo '${{ secrets.biliconfig }}' > ./config/config.json && python3 check.py
      
    - name: 安装Funcraft
      run: wget --no-check-certificate -O fun-linux.zip https://gosspublic.alicdn.com/fun/fun-v3.6.14-linux.zip && unzip fun-linux.zip && sudo mv fun-*-linux /usr/local/bin/fun && rm fun-linux.zip
    
    - name: 部署至阿里云
      run: fun deploy -t aliyun-serverless-template.yml || (echo '检查到部署程序异常退出，请检查阿里云函数三个参数是否配置正确(key名带下划线)，请不要使用子账户，并确认云函数计算功能已开启(云函数启用网址https://www.aliyun.com/product/fc/)' && exit -1)
      env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          REGION: cn-shanghai
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
